FROM node:20.18.1-alpine3.20 AS pkg
WORKDIR /app
COPY . .
RUN sh ./scripts/cp-pkg.sh
FROM node:20.18.1-alpine3.20 AS build
WORKDIR /app
COPY --from=pkg /app/.pkg /app
RUN npm ci
COPY . .
RUN npx nx build client
FROM nginx:1.27.3-alpine3.20
COPY ./apps/client/chat.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/apps/client/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
 