services:
  client:
    image: alontzafari/chatty-client:1.0.0
    restart: always
    expose:
      - 80
    environment:
      - API_HOST=api:8080
    networks:
      - ingress
      - chat
  api:
    image: alontzafari/chatty-api:1.0.0
    restart: always
    expose:
      - 8080
    environment:
    - DB_URI=${DB_URI}
    - PORT=8080
    - ADDRESS=0.0.0.0
    networks:
      - chat

networks:
  chat: