services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    profiles:
      - infra
    volumes:
      - pg:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=alontzafari@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    profiles:
      - infra
    

volumes:
  pg: 