name: Chatty Workflow

on: 
  push:
    branches: ['main', 'feature/**', 'fix/**']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx nx run-many -t test
  build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg:
          - client
          - api 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build
        run: npm run docker-build -w apps/${{ matrix.pkg }}
      - name: push
        run: npm run docker-push -w apps/${{ matrix.pkg }}
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: prod 
    env:
      ALONTZ_DEV_KEY: ${{ secrets.ALONTZ_DEV_KEY }}
      ALONTZ_HOST: ${{ vars.ALONTZ_HOST }}
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: ./scripts/deploy.sh
        